name: "PR comment HEAD branch"
description: "Sets a 'head_branch' output if the workflow was dispatched on a PR comment"

runs:
  using: "composite"
  steps:
    - name: "Get HEAD branch"
      id: get_head_branch
      if: github.event_name == 'issue_comment' && github.event.issue.pull_request
      uses: actions/github-script@v6
      with:
        script: |
          const pr_number = context.payload.issue.number;
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr_number
          });
          core.exportVariable('PR_COMMENT_HEAD_BRANCH', pr.head.ref);

    - name: "Set output"
      if: steps.get_head_branch.outcome == 'success'
      shell: bash
      run: |
        echo "PR comment HEAD branch: ${{ env.PR_COMMENT_HEAD_BRANCH }}"
        echo "head_branch=${{ env.PR_COMMENT_HEAD_BRANCH }}" >> "$GITHUB_OUTPUT"