name: "PR comment HEAD branch"
description: "Sets a 'head_branch' output if the workflow was dispatched on a PR comment"

outputs:
  head_branch:
    description: "PR HEAD branch name"
    value: ${{ steps.get_head_branch.outputs.head_branch }}

runs:
  using: "composite"
  steps:
    - name: "Get HEAD branch"
      id: get_head_branch
      if: github.event_name == 'issue_comment' && github.event.issue.pull_request
      uses: actions/github-script@v6
      with:
        script: |
          const pr_number = context.payload.issue.number;
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr_number
          });
          core.exportVariable('GITHUB_OUTPUT', `head_branch=${pr.head.ref}`);

    - name: "Check output"
      id: check_output 
      if: steps.set_output.outcome == 'success'
      shell: bash
      run: |
        echo "steps.set_output.outputs.head_branch: ${{ steps.set_output.outputs.head_branch }}"
