name: Test
on:
  pull_request:

jobs:
  odbc-vendoring-dispatch:
    name: ODBC vendoring dispatch 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Merge vendoring PR
        id: merge_vendoring_pr
        if: ${{ github.repository == 'staticlibs/duckdb-odbc' && github.event_name == 'pull_request' && github.head_ref == 'vendoring' }}
        run: |
            # Store the PAT in a file that can be accessed by the
            # GitHub CLI.
            echo "${{ secrets.PAT_TOKEN }}" > token.txt
            # Authorize GitHub CLI for the current repository and
            # create a pull-requests containing the updates.
            gh auth login --with-token < token.txt
            gh pr merge vendoring \
             --rebase \
             --subject "${{ github.event.pull_request.title }}" \
             --body ""
