name: Test
on:
  issue_comment:

jobs:
  odbc-linux-amd64:
    name: ODBC Linux (amd64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if this is a pull request comment
        id: check_pr
        if: ${{ github.event.issue.pull_request }}
        run: echo "This is a pull request comment."

      - name: Get PR HEAD branch name
        id: get_pr_details
        if: steps.check_pr.conclusion == 'success'
        uses: actions/github-script@v6
        with:
          script: |
            const pr_number = context.payload.issue.number;
            const { data: pr } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });
            return { head_branch: pr.head.ref };

      - name: Merge
        if: github.repository == 'staticlibs/duckdb-odbc' && steps.get_pr_details.outputs.head_branch == 'vendoring'
        shell: bash
        run: |
            # Store the PAT in a file that can be accessed by the
            # GitHub CLI.
            echo "${{ secrets.GH_TOKEN }}" > token.txt
            # Authorize GitHub CLI for the current repository and
            # create a pull-requests containing the updates.
            gh auth login --with-token < token.txt
            gh pr merge vendoring \
             --subject "${{ github.event.comment.body }}" \
             --body "" \
             --rebase
            git push --delete origin vendoring
            git branch vendoring
            git push -f origin vendoring
