name: Test
on:
  pull_request:

jobs:
  odbc-vendoring-dispatch:
    name: ODBC vendoring dispatch 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Merge vendoring PR
        id: merge_vendoring_pr
        if: ${{ github.repository == 'staticlibs/duckdb-odbc' && github.event_name == 'pull_request' && github.head_ref == 'vendoring' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            # echo "Merging PR number: ${{ github.event.pull_request.number }} with message: ${{ github.event.pull_request.title }}"
            gh pr merge vendoring \
             --rebase \
             --subject "${{ github.event.pull_request.title }}" \
             --body ""
            # Delete vendoring barnch and re-create it for future PRs
            git push --delete origin vendoring
            git checkout --track origin/main
            git pull  --ff-only
            git branch vendoring
            git push origin vendoring
